name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 14 * * 1-5'  # Run at 2 PM UTC (9 AM EST) Monday-Friday
  workflow_dispatch:  # Allows manual running

jobs:
  analyze-stocks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run stock analysis
      env:
        ALPHA_VANTAGE_API_KEY: ${{ secrets.ALPHA_VANTAGE_API_KEY }}
      run: python stock_analysis.py
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: stock-analysis-results
        path: "*.csv"
        retention-days: 30
