name: Daily Stock Analysis

on:
  schedule:
    - cron: '0 14 * * 1-5'  # Run at 2 PM UTC (9 AM EST) Monday-Friday
  workflow_dispatch:  # Allows manual running

jobs:
  analyze-stocks:
    runs-on: ubuntu-latest

    env:
      TWELVEDATA_API_KEY: ${{ secrets.TWELVEDATA_API_KEY }}    
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Show current directory
      run: pwd

    - name: List all files
      run: ls -R
      
    - name: Run stock analysis
      run: python EMAX.py
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: stock-analysis-results
        path: "*.csv"
        retention-days: 10

    - name: Commit and push results
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add stock_analysis_results.csv
        git commit -m "Update stock analysis results"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/gdharnigit/EMAX.git HEAD:main

